[package]
org = "ballerina"
name = "constraint"
version = "1.0.0"
authors = ["Ballerina"]
keywords = ["constraint", "validation"]
repository = "https://github.com/ballerina-platform/module-ballerina-constraint"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.4"

[[platform.java11.dependency]]
path = "../native/build/libs/constraint-native-1.0.0-SNAPSHOT.jar"
