name: Build with bal test native

on:
    workflow_dispatch:
        inputs:
            build_envs:
                description: Test Environments
                type: choice
                required: true
                options:
                    - Ubuntu
                    - Windows
                    - Ubuntu and Windows
                default: Ubuntu and Windows
            lang_tag:
                description: Branch/Release Tag of the Ballerina Lang
                required: true
                default: master
            lang_version:
                description: Ballerina Lang Version (If given ballerina lang buid will be skipped)
                required: false
                default: ''
            native_image_options:
                description: Default native-image options
                required: false
                default: ''
    schedule:
        -   cron: '30 18 * * *'

jobs:
    call_stdlib_workflow:
        name: Run StdLib Workflow
        uses: ballerina-platform/ballerina-standard-library/.github/workflows/build-with-bal-test-native-template.yml@main
        with:
            build_envs: ${{ inputs.build_envs }}
            lang_tag: ${{ inputs.lang_tag }}
            lang_version: ${{ inputs.lang_version }}
            native_image_options: ${{ inputs.native_image_options }}
